### ISSUE TITLE
Code Reuse(allow partial reuse)

### ISSUE THREAD

**Issue by modaresimr** [roborescue/rcrs-rules#1]
Currently, we have a problem that TDP submission time has a long distance to the time of holding the competition which the information in TDP is almost wrong. Therefore, I think we should get more information from teams about 1 month before the competition about the partial use of other team's source code and the percentage of changes and what is their change and what is the effect of their change. otherwise, they will be disqualified

**Comment by modaresimr** [comment]
Luis: We tried to implement it last year by requesting an updated version of the TDP, ....... We can motivate teams to be more scientific and precise on their description, but how can we enforce it?

**Comment by modaresimr** [comment]
i think for each reused module, we can force teams to prepare a description PDF otherwaise, if they use a module from another team they will be disqualified.

**Comment by modaresimr** [comment]
Luis: We can instruct the teams to list all the modules they reused explicitly.

**Comment by gnardin** [comment]
Included Code Reuse in the 2019 Rules
