### ISSUE TITLE
Changing the TDP Template

### ISSUE THREAD

**Issue by modaresimr** [roborescue/rcrs-rules#2]
think it is better to force teams to use some external references and force them to have more scientific paper. ....... i think it could be a good start.
I think Each section of the TDP should contain: 1-A summary of related scientific papers about the problems in this section. 2-What other teams did last year(not only what they said on TDP), 3-what is the team's approach, 4-provide their cons and props.

**Comment by gnardin** [comment]
These suggestions have been included in the structure of the TDP templates.
